name: Sync Fork

env:
  ORIGINAL_OWNER: opentdp
  ORIGINAL_REPOSITORY: tdp-cloud
  UPSTREAM_BRANCH: main
  MY_BRANCH: main

on:
  # push:
  # branches:
  #   - my #指定运行分支
  # schedule:
  #   - cron:  '0 0 * * *'  # 每天凌晨运行
  workflow_dispatch: #手工运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/${{ env.ORIGINAL_OWNER }}/${{ env.ORIGINAL_REPOSITORY }}.git
        git fetch upstream
        git checkout ${{ env.MY_BRANCH }}
        git merge upstream/${{ env.UPSTREAM_BRANCH }}
      
  

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MYGITHUB_TOKEN }}
        branch: ${{ github.ref }}

  release:
    needs: sync
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Release
      id: latest_release
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: ${{ env.ORIGINAL_OWNER }}
        repo: ${{ env.ORIGINAL_REPOSITORY }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest_release.outputs.tag_name }}
        release_name: Release ${{ steps.latest_release.outputs.tag_name }}
        body: ${{ steps.latest_release.outputs.body }}
        draft: false
        prerelease: false
