name: Sync Fork

env:
  ORIGINAL_OWNER: opentdp
  ORIGINAL_REPOSITORY: tdp-cloud
  UPSTREAM_BRANCH: main
  MY_BRANCH: main

on:
  # push:
  # branches:
  #   - my #指定运行分支
  # schedule:
  #   - cron:  '0 0 * * *'  # 每天凌晨运行
  workflow_dispatch: #手工运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/${{ env.ORIGINAL_OWNER }}/${{ env.ORIGINAL_REPOSITORY }}.git
        git fetch upstream
        git checkout -b ${{ env.MY_BRANCH }} upstream/${{ env.UPSTREAM_BRANCH }}
        git reset --hard upstream/${{ env.UPSTREAM_BRANCH }}
      
  
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MYGITHUB_TOKEN }}
        branch: ${{ env.MY_BRANCH }}
        force: true

  release:
    needs: sync
    runs-on: ubuntu-latest
    steps:

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Get Latest Release
      id: latest_release
      run: |
        response=$(curl --silent "https://api.github.com/repos/${{ env.ORIGINAL_OWNER }}/${{ env.ORIGINAL_REPOSITORY }}/releases/latest")
        echo "::set-output name=tag_name::$(echo $response | jq -r .tag_name)"
        echo "::set-output name=body::$(echo $response | jq -r .body)"
        echo "::set-output name=assets_url::$(echo $response | jq -r .assets_url)"

        - name: Check if release exists and is new
        id: check_release
        run: |
          if [[ -z "${{ steps.latest_release.outputs.tag_name }}" ]]; then
            echo "No release found in the upstream repository. Skipping release creation."
            echo "::set-output name=skip::true"
          else
            echo "获取到的tag是：${{ steps.latest_release.outputs.tag_name }}"
            echo "Release found in the upstream repository. Checking if it's new."
            curl -f --silent "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.latest_release.outputs.tag_name }}" > /dev/null
            if [[ "$?" -ne 0 ]]; then
              echo "New release found. Proceeding with release creation."
              echo "::set-output name=skip::false"
            else
              echo "Release already exists in the local repository. Skipping release creation."
              echo "::set-output name=skip::true"
            fi
          fi
      

    - name: Create Release
      id: create_release
      if: steps.check_release.outputs.skip == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest_release.outputs.tag_name }}
        release_name: Release ${{ steps.latest_release.outputs.tag_name }}
        body: ${{ steps.latest_release.outputs.body }}
        draft: false
        prerelease: false

    - name: Download and Upload Release Assets
      if: steps.check_release.outputs.skip == 'false'
      run: |
        assets=$(curl --silent "${{ steps.latest_release.outputs.assets_url }}")
        asset_ids=$(echo $assets | jq -r '.[].id')
        for asset_id in $asset_ids; do
          asset=$(curl --silent "https://api.github.com/repos/${{ env.ORIGINAL_OWNER }}/${{ env.ORIGINAL_REPOSITORY }}/releases/assets/$asset_id")
          asset_url=$(echo $asset | jq -r '.browser_download_url')
          asset_name=$(echo $asset | jq -r '.name')
          curl -LJO $asset_url
          gh release upload ${{ steps.latest_release.outputs.tag_name }} $asset_name --repo ${{ github.repository }}
        done
